# Generated by Django 6.0.3 on 2026-03-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
